// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/complex-cors/_middleware.ts";
import * as $1 from "./routes/api/complex-cors/index.ts";
import * as $2 from "./routes/api/no-cors/index.ts";
import * as $3 from "./routes/api/simple-cors/_middleware.ts";
import * as $4 from "./routes/api/simple-cors/index.ts";

const manifest = {
  routes: {
    "./routes/api/complex-cors/_middleware.ts": $0,
    "./routes/api/complex-cors/index.ts": $1,
    "./routes/api/no-cors/index.ts": $2,
    "./routes/api/simple-cors/_middleware.ts": $3,
    "./routes/api/simple-cors/index.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
